

check: checking working properly
spring:
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: news
          uri: http://localhost:8081 
          predicates:
            - Path=/news/**
management:
  tracing:
    sampling:
      probability: 1.0
